### ISSUE TITLE
Sometimes this plugin has a problem that video does not start.

### ISSUE THREAD

**Issue by kyungjoongo** [sarbagyastha/youtube_player#18]
Sometimes this plugin has a problem that video does not start.
Often, it takes a long time to load, or only the video loading indicator appears and playback is not possible.
However, it does not exactly cause Exception.
Is there a way to fix it?

**Comment by sarbagyastha** [comment]
Sometime it might take little more time to load video as flutter engine needs to  texture paint the whole video into flutter view. Also, it might be due to network fluctuation. 
But if the loading indicator appears and playback is not possible then it might be an issue with specific videos. Can you mention such video's id ?
